tonic = 40
lowest = tonic - 12
highest = tonic + 16
positions = {tonic - 12: "I-",
             tonic - 11: "bII-",
             tonic - 10: "II-",
             tonic - 9: "bIII-",
             tonic - 8: "III-",
             tonic - 7: "IV-",
             tonic - 6: "bV-",
             tonic - 5: "V-",
             tonic - 4: "bVI-",
             tonic - 3: "VI-",
             tonic - 2: "bVII-",
             tonic - 1: "VII-",
             tonic:     "I",
             tonic + 1: "bII",
             tonic + 2: "II",
             tonic + 3: "bIII",
             tonic + 4: "III",
             tonic + 5: "IV",
             tonic + 6: "bV",
             tonic + 7: "V",
             tonic + 8: "bVI",
             tonic + 9: "VI",
             tonic + 10: "bVII",
             tonic + 11: "VII",
             tonic + 12: "I+",
             tonic + 13: "bII+",
             tonic + 14: "II+",
             tonic + 15: "bIII+",
             tonic + 16: "III+",
             tonic + 17: "IV+",
             tonic + 18: "bV+",
             tonic + 19: "V+",
             tonic + 20: "bVI+",
             tonic + 21: "VI+",
             tonic + 22: "bVII+",
             tonic + 23: "VII+",}

notenumbers = {
             "I-": tonic - 12,
             "bII-": tonic - 11,
             "II-": tonic - 10,
             "bIII-": tonic - 9,
             "III-": tonic - 8,
             "IV-": tonic - 7,
             "bV-": tonic - 6,
             "V-": tonic - 5,
             "bVI-": tonic - 4,
             "VI-": tonic - 3,
             "bVII-": tonic - 2,
             "VII-": tonic - 1,
             "I": tonic,
             "bII": tonic + 1,
             "II": tonic + 2,
             "bIII": tonic + 3,
             "III": tonic + 4,
             "IV": tonic + 5,
             "bV": tonic + 6,
             "V": tonic + 7,
             "bVI": tonic + 8,
             "VI": tonic + 9,
             "bVII": tonic + 10,
             "VII": tonic + 11,
             "I+": tonic + 12,
             "bII+": tonic + 13,
             "II+": tonic + 14,
             "bIII+": tonic + 15,
             "III+": tonic + 16,
             "IV+": tonic + 17,
             "bV+": tonic + 18,
             "V+": tonic + 19,
             "bVI+": tonic + 20,
             "VI+": tonic + 21,
             "bVII+": tonic + 22,
             "VII+": tonic + 23,}